"""create incidents, action plans, tasks and history

Revision ID: 721a74180808
Revises: c0c3a47c91cd
Create Date: 2026-10-01 15:42:03.489952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721a74180808'
down_revision: Union[str, Sequence[str], None] = 'c0c3a47c91cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_analysis', 'corrective_action', 'closed', name='status', native_enum=False, create_constraint=True, length=30), server_default='open', nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by_id'], ['users.id'], name=op.f('fk_incidents_analyzed_by_id_users')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_incidents_part_id_parts')),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], name=op.f('fk_incidents_reported_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_part_id'), 'incidents', ['part_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_action_plans_created_by_id_users')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_action_plans_incident_id_incidents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_plans')),
    sa.UniqueConstraint('incident_id', name=op.f('uq_action_plans_incident_id'))
    )
    op.create_table('incident_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('from_status', sa.Enum('open', 'in_analysis', 'corrective_action', 'closed', name='from_status', native_enum=False, create_constraint=True, length=30), nullable=True),
    sa.Column('to_status', sa.Enum('open', 'in_analysis', 'corrective_action', 'closed', name='to_status', native_enum=False, create_constraint=True, length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_history_incident_id_incidents')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_incident_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_history'))
    )
    op.create_index(op.f('ix_incident_history_incident_id'), 'incident_history', ['incident_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_plan_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], name=op.f('fk_tasks_action_plan_id_action_plans')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_tasks_assigned_to_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_action_plan_id'), 'tasks', ['action_plan_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_action_plan_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_incident_history_incident_id'), table_name='incident_history')
    op.drop_table('incident_history')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_part_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
